import "./globals.css";
import localFont from "next/font/local";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pelak = localFont({
  src: [
    {
      path: "../public/fonts/PelakFA-Regular.woff2",
      weight: "400",
    },
  ],
  variable: "--font-pelak",
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="fa-IR" dir="rtl">
      <body className={pelak.variable}>{children}</body>
    </html>
  );
}
